-- Reset and update training scenarios and scenario lines
-- Created on 3/24/2025

-- First, delete all existing data from related tables in the correct order to respect foreign key constraints
-- Delete feedback records that reference training_sessions
DELETE FROM feedback WHERE training_session_id IN (SELECT id FROM training_sessions);

-- Delete training_sessions that reference training_scenarios
DELETE FROM training_sessions WHERE scenario_id IN (SELECT id FROM training_scenarios);

-- Now we can safely delete scenario_lines and training_scenarios
DELETE FROM scenario_lines;
ALTER TABLE scenario_lines AUTO_INCREMENT = 1;

DELETE FROM training_scenarios;
ALTER TABLE training_scenarios AUTO_INCREMENT = 1;

-- Insert new training scenarios from the updated CSV
INSERT INTO training_scenarios (id, title, description, difficulty, category, audio_filter_type, created_at, updated_at, is_active)
VALUES 
(1, 'Basic Radio Check', 'Practice conducting a simple radio check to verify communications', 'beginner', 'communications', 'radio', NOW(), NOW(), TRUE),
(2, 'Checkpoint Security Incident', 'Practice reporting a security breach at a checkpoint with proper radio procedure', 'intermediate', 'reports', 'radio', NOW(), NOW(), TRUE),
(3, 'Vehicle Recovery Request', 'Practice requesting vehicle recovery using standard radio protocols', 'beginner', 'logistics', 'radio', NOW(), NOW(), TRUE),
(4, 'Unit Status Report', 'Practice delivering a concise unit status report under combat conditions', 'intermediate', 'reports', 'static', NOW(), NOW(), TRUE),
(5, 'Weather Report Transmission', 'Practice transmitting and receiving detailed weather information reports', 'intermediate', 'reports', 'radio', NOW(), NOW(), TRUE),
(6, 'Casualty Evacuation Procedure', 'Practice medical evacuation procedures including MIST reports and 9-liners', 'advanced', 'medical', 'static', NOW(), NOW(), TRUE),
(7, 'Ammunition Status and Resupply', 'Practice reporting ammunition status and requesting resupply using AMMOCAZ format', 'intermediate', 'logistics', 'radio', NOW(), NOW(), TRUE);

-- Insert scenario lines for Basic Radio Check (scenario_id = 1)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(1, 1, 1, 1, 'Alpha-2, this is Zero. Radio check. Over.', NULL, 'You are conducting a basic radio check with Zero station to verify communications are working properly. This is a standard procedure to ensure clear communications before operations begin.', '0', NOW(), NOW()),
(2, 1, 2, 0, NULL, 'Zero, this is Alpha-2. I read you Lima Charlie. Over.', 'You are conducting a basic radio check with Zero station to verify communications are working properly. This is a standard procedure to ensure clear communications before operations begin.', NULL, NOW(), NOW()),
(3, 1, 3, 1, 'Alpha-2, this is Zero. Roger, I read you Lima Charlie as well. How copy? Over.', NULL, 'You are conducting a basic radio check with Zero station to verify communications are working properly. This is a standard procedure to ensure clear communications before operations begin.', '0', NOW(), NOW()),
(4, 1, 4, 0, NULL, 'Zero, this is Alpha-2. Good copy. Out.', 'You are conducting a basic radio check with Zero station to verify communications are working properly. This is a standard procedure to ensure clear communications before operations begin.', NULL, NOW(), NOW());

-- Insert scenario lines for Checkpoint Security Incident (scenario_id = 2)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(5, 2, 1, 0, 'This is 1 Alpha, Contact wait out', NULL, 'You have Just made contact with the enemy', '1A', NOW(), NOW()),
(6, 2, 2, 0, NULL, '0, THIS IS 1 Alpha   – Contact Report. OVER.', 'A military or security checkpoint was established at or near grid coordinates 38S WA 2311 6755. Alpha 1 is security element, was manning this checkpoint.\n\nAt approximately 11:20 AM UTC (Zulu time) on the 10th day of the current month, a pickup truck with two occupants approached the checkpoint. When signaled to stop, the vehicle failed to comply with the stop order and continued through the checkpoint without authorization.\n\nIn response to this security breach, Alpha 1''s personnel fired shots at the vehicle. Despite the shots, the pickup truck continued driving away from the checkpoint, ', NULL, NOW(), NOW()),
(7, 2, 3, 1, '1 Alpha, THIS IS 0 – SEND. OVER', NULL, 'A military or security checkpoint was established at or near grid coordinates 38S WA 2311 6755. Alpha 1 is security element, was manning this checkpoint.\n\nAt approximately 11:20 AM UTC (Zulu time) on the 10th day of the current month, a pickup truck with two occupants approached the checkpoint. When signaled to stop, the vehicle failed to comply with the stop order and continued through the checkpoint without authorization.\n\nIn response to this security breach, Alpha 1''s personnel fired shots at the vehicle. Despite the shots, the pickup truck continued driving away from the checkpoint, ', '0', NOW(), NOW()),
(8, 2, 4, 0, NULL, 'para alpha: 10 1120 ZULU\n para bravo: GRID – 38S WA 2311 6755\n para charlie: GRID – 38S WA 2311 6722\n para delta: 2x enemy in pick up truck, \n para echo: VEHICLE FAILED TO STOP AT CHECKPOINT and Drove away\n para foxtrot: SHOTS FIRED', 'A military or security checkpoint was established at or near grid coordinates 38S WA 2311 6755. Alpha 1 is security element, was manning this checkpoint.\n\nAt approximately 11:20 AM UTC (Zulu time) on the 10th day of the current month, a pickup truck with two occupants approached the checkpoint. When signaled to stop, the vehicle failed to comply with the stop order and continued through the checkpoint without authorization.\n\nIn response to this security breach, Alpha 1''s personnel fired shots at the vehicle. Despite the shots, the pickup truck continued driving away from the checkpoint, ', NULL, NOW(), NOW()),
(9, 2, 5, 1, '1 Alpha, THIS IS 0 Roger OUT.', NULL, 'A military or security checkpoint was established at or near grid coordinates 38S WA 2311 6755. Alpha 1 is security element, was manning this checkpoint.\n\nAt approximately 11:20 AM UTC (Zulu time) on the 10th day of the current month, a pickup truck with two occupants approached the checkpoint. When signaled to stop, the vehicle failed to comply with the stop order and continued through the checkpoint without authorization.\n\nIn response to this security breach, Alpha 1''s personnel fired shots at the vehicle. Despite the shots, the pickup truck continued driving away from the checkpoint, ', '0', NOW(), NOW());

-- Insert scenario lines for Vehicle Recovery Request (scenario_id = 3)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(10, 3, 1, 1, 'Alpha 1 Send Repair Recovery Request', NULL, 'Your LSVW has broken down and will not start. It cannot be moved while you are going to the next location, and you are Alpha 1, the 0 post for 15 Infantry. You are at GR ML 1893 2748. There are three people in the vehicle; there is no enemy, but the road is extremely muddy.', '0', NOW(), NOW()),
(11, 3, 2, 0, NULL, '0 this is Alpha1 Repair Recovery Request over', 'Your LSVW has broken down and will not start. It cannot be moved while you are going to the next location, and you are Alpha 1, the 0 post for 15 Infantry. You are at GR ML 1893 2748. There are three people in the vehicle; there is no enemy, but the road is extremely muddy.', NULL, NOW(), NOW()),
(12, 3, 3, 1, 'Alpha 1 this 0 , send over ', NULL, 'Your LSVW has broken down and will not start. It cannot be moved while you are going to the next location, and you are Alpha 1, the 0 post for 15 Infantry. You are at GR ML 1893 2748. There are three people in the vehicle; there is no enemy, but the road is extremely muddy.', '0', NOW(), NOW()),
(13, 3, 4, 0, NULL, 'Para Alpha: Recovery.\n\nPara Bravo: NIL\n\nPara Charlie: Pappa for 15 infantry, LSVW Alpha-1, 168392.\n\nPara Delta: ML 1893 2748, Alpha-1.\n\nPara Echo: Vehicle will not move or start.\n\nPara Foxtrot: Vehicle will not start.\n\nPara Golf: Non-tactical road is extremely muddy.\n\nPara Hotel: Crew of 3 is with the vehicle.\n\nPara India: ML 1893 2748.', 'Your LSVW has broken down and will not start. It cannot be moved while you are going to the next location, and you are Alpha 1, the 0 post for 15 Infantry. You are at GR ML 1893 2748. There are three people in the vehicle; there is no enemy, but the road is extremely muddy.', NULL, NOW(), NOW()),
(14, 3, 5, 1, '0, Acknowledged out', NULL, NULL, '0', NOW(), NOW());

-- Insert scenario lines for Unit Status Report (scenario_id = 4)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(15, 4, 1, 1, 'Alpha-1  this is 0 send sitrep over ', NULL, '0 wants to know the status of your unit. You are at grid 1657 1132. Your unit has had several contacts with the enemy and has exhausted its ammunition supply, and a lot of equipment has been damaged or destroyed. You can not continue without more ammo and to replace and repair the equipment ', '0', NOW(), NOW()),
(16, 4, 2, 0, NULL, '0, this is Alpha-1.\nPara Alpha, unknown.\nPara Bravo, Grid 1657 1132. 45 personnel, normal operations.\nPara Charlie, ammo status is critically low.\nPara Delta, combat ineffective due to lack of ammo and damaged/destroyed equipment. Over.', '0 wants to know the status of your unit. You are at grid 1657 1132. Your unit has had several contacts with the enemy and has exhausted its ammunition supply, and a lot of equipment has been damaged or destroyed. You can not continue without more ammo and to replace and repair the equipment', NULL, NOW(), NOW()),
(17, 4, 3, 1, '0, Roger Out', NULL, '0 wants to know the status of your unit. You are at grid 1657 1132. Your unit has had several contacts with the enemy and has exhausted its ammunition supply, and a lot of equipment has been damaged or destroyed. You can not continue without more ammo and to replace and repair the equipment', '0', NOW(), NOW());

-- Insert scenario lines for Weather Report Transmission (scenario_id = 5)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(18, 5, 1, 1, 'Alpha-1 this is Alpha-1echo send metrep over ', NULL, 'NOTE THIS WILL BE A LONG MESSAGE, You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', 'A1E', NOW(), NOW()),
(19, 5, 2, 0, NULL, 'Alpha-1 echo this is alpha 1 long message metrep over ', 'NOTE THIS WILL BE A LONG MESSAGE, You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', NULL, NOW(), NOW()),
(20, 5, 3, 1, 'Alpha -1 echo send over ', NULL, 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', 'A1E', NOW(), NOW()),
(21, 5, 4, 0, NULL, 'Para Alpha: CFB Downrange.\n\nPara Bravo: Next 24 hours:\n\nSub Para Alpha: Precipitation PoP 32%.\nSub Para Bravo: Wind from NW at 25-30 kph.\nSub Para Charlie: High of +4°C, low of -11°C.\nPara Charlie: Next 24 hours:\n\nSub Para Alpha: 0 mm, PoP 30%.\nSub Para Bravo: Wind from North at 20-30 kph.\nSub Para Charlie: High of -8°C, low of -20°C.\nPara Delta: Temperature continues to drop.\n\nPara Echo:\n\nAlpha: 0830\nBravo: 1940\nCharlie: New moon\nDelta: 2000\nEcho: 0500\nOver.', 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', NULL, NOW(), NOW()),
(22, 5, 5, 1, 'Alpha-1 echo say again all after para Delta over ', NULL, 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', 'A1E', NOW(), NOW()),
(23, 5, 6, 0, NULL, 'Alpha 1, I say again: Para Delta, Alpha 0830, Bravo 1940, Charlie new moon, Delta 2000, Echo 0500, over.', 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', NULL, NOW(), NOW()),
(24, 5, 7, 1, 'Alpha-1 echo roger over ', NULL, 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', 'A1E', NOW(), NOW()),
(25, 5, 8, 0, NULL, 'Alpha-1, Rogger out.', 'You call up Environment Canada, and they tell you that for CFB Downrange , over the next 24 hours, there has been no precipitation and the probability of precipitation (PoP) is 32%. The current temperature is 4°C but is expected to fall to a low of - 11°C. Winds are from the NW at 25 kph but are expected to increase to 30 kph and swing to the north. First light is at 8:30 AM and last light is at 7:40 PM. Moon phase is New Moon, rise at 10 PM and set at 5:00 AM. The extended forecast is for temperatures to continue to fall tomorrow, with a high of - 10°C and a low of - 25°C, with winds from 20 to 30 kph and a PoP of 30%. The day after, the temperature will have a high of -8°C and a low of -20°C with a PoP of 30%.', NULL, NOW(), NOW());

-- Insert scenario lines for Casualty Evacuation Procedure (scenario_id = 6)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(26, 6, 1, 0, NULL, 'Zero, this is 2 Bravo - MIST report Over.', NULL, NULL, NOW(), NOW()),
(27, 6, 2, 1, '2 Bravo this is Zero. Send MIST. Over.', NULL, NULL, '0', NOW(), NOW()),
(28, 6, 3, 0, NULL, 'M: Vehicle struck IED at 38S LA 4532 7891, passenger side impact\nI: One casualty, 25-year-old male with lower right leg trauma and facial lacerations\nS: Patient conscious, BP 100/70, pulse 110, respirations 22, GCS 15\nT: Tourniquet applied to right leg, hemorrhage controlled, wound dressed, 500ml Ringer''s initiated, morphine 10mg administered Over.', NULL, NULL, NOW(), NOW()),
(29, 6, 4, 1, '2 Bravo, this is Zero. MIST received. Surgical team will be notified. Over.', NULL, NULL, '0', NOW(), NOW()),
(30, 6, 5, 0, NULL, 'Zero, this is 2 Bravo. Roger, out', 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', NULL, NOW(), NOW()),
(31, 6, 6, 1, '2 Bravo, this is Zero. MIST received. Prepare 9-liner for immediate MEDEVAC. Over.', NULL, 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', '0', NOW(), NOW()),
(32, 6, 7, 0, NULL, 'Zero, this is 2 Bravo. 9-liner  over', 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', NULL, NOW(), NOW()),
(33, 6, 8, 1, '2 Bravo, this is Zero. Send 9-Liner. Over.', NULL, 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', '0', NOW(), NOW()),
(34, 6, 9, 0, NULL, 'Line 1: Grid 38S LA 4532 7891\nLine 2: LZ Whiskey, freq 68.5, call sign Dagger\nLine 3: 1 urgent, 3 priority\nLine 4: Special equipment: None\nLine 5: 4 litter\nLine 6: Security at LZ: Green\nLine 7: Marking: Orange smoke\nLine 8: Patient nationality: US military\nLine 9: NBC: None', 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', NULL, NOW(), NOW()),
(35, 6, 10, 1, '2 Bravo, this is Zero. 9-line received. MEDEVAC inbound, ETA 18 minutes. Maintain security. Over.', NULL, 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', '0', NOW(), NOW()),
(36, 6, 11, 0, NULL, 'Zero, this is 2 Bravo. Roger, out.', 'Bravo 2 patrol''s lead HMMWV struck pressure-plate IED at grid 38S LA 4532 7891 at 0743L/0443Z on 15MAR. Vehicle rolled after 1.5m lift. Four casualties total - front passenger (SGT Miller) critical with traumatic right leg amputation below knee, facial lacerations from fragmentation, and suspected pneumothorax. Patient conscious but in shock - BP 90/60 dropping, pulse 125 and thready, respirations 28 and labored, O2 sat 92%, GCS 14 (E4V4M6). Combat medic applied CAT tourniquet to right leg, needle decompression left chest, established 18G IV with 2x 500ml Ringer''s wide open, administered 10mg morphine and 1g TXA. ', NULL, NOW(), NOW());

-- Insert scenario lines for Ammunition Status and Resupply (scenario_id = 7)
INSERT INTO scenario_lines (id, scenario_id, line_number, is_prompter, prompter_text, user_text, phase_context, prompter_callsign, created_at, updated_at)
VALUES
(37, 7, 1, 1, '5 Lima, this is Zero. Request AMMOCAZ status. Over.', NULL, 'You are Lima 5 weapons squad, 1st Platoon, C Company at COP IRON. After a 35-minute firefight yesterday where you expended significant 7.62mm ammunition from your M240Bs, multiple 60mm mortar rounds, and numerous smoke grenades, your platoon leader has ordered an AMMOCAZ report. You must request resupply before tomorrow''s convoy arrival (callsign BRAVO) to prepare for an operation in 36 hours. You''ve counted all ammunition 30 minutes ago and identified critical shortages in 7.62mm, 60mm HE, and smoke grenades.', '0', NOW(), NOW()),
(38, 7, 2, 0, NULL, 'Zero, this is 5 Lima. AMMOCAZ follows. Over.', 'You are Lima 5 weapons squad, 1st Platoon, C Company at COP IRON. After a 35-minute firefight yesterday where you expended significant 7.62mm ammunition from your M240Bs, multiple 60mm mortar rounds, and numerous smoke grenades, your platoon leader has ordered an AMMOCAZ report. You must request resupply before tomorrow''s convoy arrival (callsign BRAVO) to prepare for an operation in 36 hours. You''ve counted all ammunition 30 minutes ago and identified critical shortages in 7.62mm, 60mm HE, and smoke grenades.', NULL, NOW(), NOW()),
(39, 7, 3, 0, NULL, 'PARA ALPHA: DTG -- 231730Z MAR 25\nPARA BRAVO: UNIT -- Lima 5, 1st Platoon, C Company\nPARA CHARLIE: LOCATION -- 38S NB 4522 6133, COP IRON\nPARA DELTA: SMALL ARMS -- 5.56mm (4200 rounds), 7.62mm (1500 rounds), 9mm (800 rounds)\nPARA ECHO: CREW SERVED -- .50 cal (2000 rounds), 40mm HEDP (120 rounds), 40mm CS (24 rounds)\nPARA FOXTROT: HAND GRENADES -- Frag (32), Smoke (22), CS (12)\nPARA GOLF: DEMOLITIONS -- C4 (20kg), Blasting caps (40), Det cord (80m)\nPARA HOTEL: MORTARS -- 60mm HE (48), 60mm Illum (24)\nPARA INDIA: AT WEAPONS -- AT4 (6), SMAW (3 HEDP, 2 Thermobaric)\nPARA JULIET: CRITICAL SHORTAGES -- 7.62mm, 60mm HE, smoke grenades\nPARA Killo: RESUPPLY REQUESTED -- 7.62mm (3000 rounds), 60mm HE (36), smoke grenades (30)\nPARA Lima: CACHE RECOVERY -- None this period. Over.', 'You are Lima 5 weapons squad, 1st Platoon, C Company at COP IRON. After a 35-minute firefight yesterday where you expended significant 7.62mm ammunition from your M240Bs, multiple 60mm mortar rounds, and numerous smoke grenades, your platoon leader has ordered an AMMOCAZ report. You must request resupply before tomorrow''s convoy arrival (callsign BRAVO) to prepare for an operation in 36 hours. You''ve counted all ammunition 30 minutes ago and identified critical shortages in 7.62mm, 60mm HE, and smoke grenades.', NULL, NOW(), NOW()),
(40, 7, 4, 1, '5 Lima, this is Zero. AMMOCAZ received. Resupply approved, ETA 240930Z via convoy BRAVO. Over.', NULL, 'You are Lima 5 weapons squad, 1st Platoon, C Company at COP IRON. After a 35-minute firefight yesterday where you expended significant 7.62mm ammunition from your M240Bs, multiple 60mm mortar rounds, and numerous smoke grenades, your platoon leader has ordered an AMMOCAZ report. You must request resupply before tomorrow''s convoy arrival (callsign BRAVO) to prepare for an operation in 36 hours. You''ve counted all ammunition 30 minutes ago and identified critical shortages in 7.62mm, 60mm HE, and smoke grenades.', '0', NOW(), NOW()),
(41, 7, 5, 0, NULL, 'Zero, this is 5 Lima. Roger. Out.', 'You are Lima 5 weapons squad, 1st Platoon, C Company at COP IRON. After a 35-minute firefight yesterday where you expended significant 7.62mm ammunition from your M240Bs, multiple 60mm mortar rounds, and numerous smoke grenades, your platoon leader has ordered an AMMOCAZ report. You must request resupply before tomorrow''s convoy arrival (callsign BRAVO) to prepare for an operation in 36 hours. You''ve counted all ammunition 30 minutes ago and identified critical shortages in 7.62mm, 60mm HE, and smoke grenades.', NULL, NOW(), NOW());
